name: Atualizar Piada Diariamente

on:
  schedule:
    - cron: '0 0 * * *' # Define a programação para rodar todos os dias à meia-noite (00:00 UTC)

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Executar script Python
        run: |
          python get_joke.py > joke.md
          git add joke.md
          git commit -m "Atualizar piada do dia"
          git push
